### ISSUE TITLE
Installation in PrivateAssemblies

### ISSUE THREAD

**Issue by sharwell** [Microsoft/VisualStudio-TestHost#2]
Why is this package installed in the IDE installation's **PrivateAssemblies** folder rather than in the user's AppData folder where other VSIX packages get installed?

**Comment by zooba** [comment]
We need to register the test adapter for the [local machine](https://github.com/Microsoft/VisualStudio-TestHost/blob/master/Installer/Product.wxs#L139) or it won't be usable for launching tests - the per-user settings are ignored by the unit test infrastructure.

The pkgdef is installed into [CommonExtensions\Platform](https://github.com/Microsoft/VisualStudio-TestHost/blob/master/Installer/Product.wxs#L172) as described in the installer - it was easier than conditionally installing in up to three locations to handle Express editions. Please don't see this as permission to install other things there :)

We install the DLL into the GAC because otherwise it'd be hard to debug assembly load errors. VS has all sorts of trickery to load assemblies from installed package directories based on the contents of the vsixmanifest file. Bypassing that mechanism for test/debug infrastructure seemed like a good idea, though since we already have our load issues sorted out, I haven't seen any direct benefits from this yet.

**Comment by sharwell** [comment]
I believe that answers the question. :+1:
